import { roboto } from "@/fonts/font";
import "./globals.css";
import SHeader from "@/components/SHeader";
import SFooter from "@/components/SFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning style={{scrollBehavior:'smooth'}}>
      <body className={`${roboto.className} flex flex-col min-h-screen bg-offWhite`}>
        <SHeader />
        <main className="pt-20 pb-4 px-4 md:px-12 lg:px-20 grow grid gap-4">{children}</main>
        <SFooter />
      </body>
    </html>
  );
}
